name: Notificacion ntfy

on:
  push:
    branches:
      - main

jobs:
  enviar-notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificacion a ntfy
        run: |
          curl -H "Title: Nueva actualizacion - Welinton Corporan" \
               -H "Content-Type: text/plain; charset=utf-8" \
               -d "Estudiante: Welinton Corporan | Matricula: 2025-1073 | Se ha subido codigo a la rama main." \
               https://ntfy.sh/devops-itla
